blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://github.com/riderx/vue-timer-hook/issues
    about: Please use the following link to create a new issue.
  - name: Github Sponsors
    url: https://github.com/sponsors/riderx
    about: Love Vue.js? Please consider supporting us via Github Sponsors.

