name: Build source code and send to Capgo

on:
  push:
    tags:
      - '*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build code and release"
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        id: install_code
        run: npm i        
      - name: Test
        id: test_code
        run: npm run test
      - name: Build
        id: build_code
        run: npm run build
      - name: Build TS
        id: build_type
        run: npm run build:dts
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
      

