name: Build source code and send to Capgo

on:
  push:
    tags:
      - '*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build code and release"
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        id: install_code
        run: pnpm install --frozen-lockfile 
      - name: Test
        id: test_code
        run: pnpm test
      - name: Build
        id: build_code
        run: pnpm build
      - name: Build TS
        id: build_type
        run: pnpm build:dts
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
      

